[COLLECTOR]
LISTENED_FILE_NAME = "./listened.csv"
MIRRORS_FILE_NAME = "./mirrors.txt"
MIRRORS_LOG_FILE_NAME = "./mirrors_log.txt"
PLAYLISTS_WITH_FAVORITES = ["^= ", "^#SYNC "]
MIRROR_PLAYLISTS_PREFIX = "++ "
DEFAULT_MIRROR_GROUP = "Mirror"
REDUCE_PERCENTAGE_OF_GOOD_TRACKS  = 5
REDUCE_MINIMUM_LISTENED_TRACKS  = 20
REDUCE_IGNORE_PLAYLISTS  = []
REDUCE_IF_NOT_UPDATED_DAYS  = 365
THREADS_COUNT = 12