[COLLECTOR]
LISTENED_FILE_NAME = "./listened.csv"
MIRRORS_FILE_NAME = "./mirrors.txt"
MIRRORS_LOG_FILE_NAME = "./mirrors_log.txt"
PLAYLISTS_WITH_FAVORITES = ["^= ", "^#SYNC "]
MIRROR_PLAYLISTS_PREFIX = "++ "
DEFAULT_MIRROR_GROUP = "Mirror"
THREADS_COUNT = 12